---
.only_on_code_change: &only_on_code_change
  only:
    changes:
      - '**/*.go'
      - '**/*.mod'
      - '**/*.sum'
      - '**/Dockefile'
      - '.gitlab-ci.yml'
      - '.gitlab-ci.yaml'
      - '*'

.only_on_helm_change: &only_on_helm_change
  only:
    changes:
      - '**/charts/**/*'

.only_on_markdown_change: &only_on_markdown_change
  only:
    changes:
      - '**/*.md'

.only_on_yaml_change: &only_on_yaml_change
  only:
    changes:
      - '**/*.yml'
      - '**/*.yaml'

include:
  - project: 'klausklausen/templates'
    ref: main
    file: 'test.yml'
  - project: 'klausklausen/templates'
    ref: main
    file: 'deploy.yml'
  - project: 'klausklausen/templates'
    ref: main
    file: 'build.yml'
  - project: 'klausklausen/templates'
    ref: main
    file: 'package.yml'
  - project: 'klausklausen/templates'
    ref: main
    file: 'deploy.yml'
  - project: 'klausklausen/templates'
    ref: main
    file: 'lint.yml'
  - project: 'klausklausen/templates'
    ref: main
    file: 'security.yml'
  - template: Jobs/SAST.gitlab-ci.yml
  - template: Jobs/Dependency-Scanning.latest.gitlab-ci.yml
  - template: Jobs/Secret-Detection.gitlab-ci.yml

variables:
  TAG: $CI_COMMIT_BRANCH
  GO_IMAGE: golang:1.23

stages:
  - lint
  - test
  - build
  - package
  - deploy
  - publish
  - security

# lint
markdown lint:
  extends: .markdown_lint
  <<: *only_on_markdown_change
yaml lint:
  extends: .yaml_lint
  <<: *only_on_yaml_change
prettier lint:
  extends: .prettier
go-lint:
  extends: .go_lint
  <<: *only_on_code_change

# security
secret_detection:
  stage: security
gitlab-advanced-sast:
  stage: security
dependency-scanning:
  stage: security
package_scan:
  extends: .package_scan
container_scan:
  extends: .container_scan
  allow_failure: true

# build
build image:
  extends: .image_multi_arch
  variables:
    IMAGE_NAME: ${NEXUS_REPO_HOST}/${CI_PROJECT_NAME}
    IMAGE_TAG: ${CI_COMMIT_SHORT_SHA}
    BUILD_TARGET: prod
  <<: *only_on_code_change

# package
package image:
  extends: .image_tag
  variables:
    IMAGE_NAME: ${NEXUS_REPO_HOST}/${CI_PROJECT_NAME}
  tags:
    - amd64
  <<: *only_on_code_change
